### PR TITLE
Hid.c clean up/rework

### PR DESCRIPTION
**Pull request by Kanuan**
Works™️ on my computer.

Simplified padding instructions, added comments, made HID descriptors easier to read.

### CODE REVIEW

**Review by nefarius — CHANGES_REQUESTED** [review]
This is not feasible; I used a parser/beautifier to generate this exact format so if there would eve be major rework changes, all these efforts are lost/overwritten so I recommend not investing in "beautifying" this blob any further.

**Comment by nefarius** [comment]
Oh, I thought the comment would stick to the single commit *sigh*

**Comment by nefarius** [comment]
Some of the properties have an effect, even if not immediately visible, we should refrain from changing too much without a full test plan like HID API, Unity engine etc. Years ago I dumped hours into this, identifying and eliminating all sorts of weird compatibility issues and I'd like to not see me do that all again because of too many changes whose sole purpose is "prettifying" 😉

**Comment by Kanuan** [comment]
unsuited commits removed

**Pull request merged**
